name: Build_Warehouse_DACPACs_$(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: dahDwh
      type: git
      name: DAH/dah_dwh
      ref: main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BuildWarehouseDACPACs
    displayName: 'Build Warehouse DACPACs'
    jobs:
      - job: BuildDACPACs
        steps:
          - checkout: dahDwh
            displayName: 'Checkout dah_dwh repository'

          - task: UseDotNet@2
            displayName: 'Use .NET SDK 6.0'
            inputs:
              packageType: 'sdk'
              version: '6.x'

          - task: DotNetCoreCLI@2
            displayName: 'Build system_wh'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/IDL/system_wh/system_wh.sqlproj'
              arguments: '--configuration Release'

          - task: DotNetCoreCLI@2
            displayName: 'Build pl_sales_pricing_dm_wh'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/CDL/OtC/pl_sales_pricing_dm_wh/pl_sales_pricing_dm_wh.sqlproj'
              arguments: '--configuration Release'

          # Kopiere DACPACs mit Workspace-Präfix für Ihr Template
          - task: CopyFiles@2
            displayName: 'Prepare system_wh DACPAC'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/IDL/system_wh/bin/Release'
              Contents: 'system_wh.dacpac'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/IDL'

          - task: CopyFiles@2
            displayName: 'Prepare pl_sales_pricing_dm_wh DACPAC'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/CDL/OtC/pl_sales_pricing_dm_wh/bin/Release'
              Contents: 'pl_sales_pricing_dm_wh.dacpac'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/CDL'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Warehouse DACPACs'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'warehouse_dacpacs'