
parameters:
- name: environment
  type: string
  default: ''

- name: azureServiceConnection
  type: string
  default: ''

- name: variableGroupName
  type: string
  default: ''

- name: ms_fabric_workspaces
  type: string
  default: ''

- name: capacityName
  type: string
  default: ''

stages:
- stage: Create_IaC_${{ parameters.environment }}
  displayName: Create IaC
  condition: and(not(failed()), not(canceled()))
  variables:
    - group: ${{ parameters.variableGroupName }}

  jobs:
  - job: CreateMsFabricWorkspaces
    displayName: Create MS Fabric new workspaces and accesses
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Install and configure bash script requirements'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Installing jq..."
          sudo apt-get update && sudo apt-get install -y jq
    - task: AzureCLI@2
      displayName: 'Create MS Fabric workspaces'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Running custom script to create workspaces..."
          ./pipelines/scripts/msfabric_create_workspaces.sh --env '${{ parameters.environment }}' --workspaces '${{ parameters.ms_fabric_workspaces }}' --capacity-name '${{ parameters.capacityName }}'  
