name: IaC_$(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ./input_vars.yaml

stages:
# Create  environment
- template: ../create_IaC_template.yaml
  parameters:
    environment: ${{ variables.environment }}
    resourceGroupName: ${{ variables.resourceGroupName }}
    bicepParamFile: ${{ variables.bicepParamFile }}
    azureServiceConnection: ${{ variables.azureServiceConnection }}
    bicepTemplateFile: ${{ variables.bicepTemplateFile }}
    pipelineValidationApprovalPerson: ${{ variables.pipelineValidationApprovalPerson }}
    variableGroupName: ${{ variables.variableGroupName }}
    ms_fabric_workspaces: ${{ variables.ms_fabric_workspaces }}
    capacityName: ${{ variables.capacityName }}
    subscriptionId: ${{ variables.subscriptionId }}
    keyvault_name: ${{ variables.keyvault_name }}
    service_principal_id  : ${{ variables.service_principal_id }}
    adf_name: ${{ variables.adf_name }}
  