name: PowerBImanageResources_$(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: dahPbi
      type: git
      name: DAH/dah_pbi
      ref: refs/heads/main

variables:
  - template: ./input_vars.yaml
  - group: ${{ variables.variableGroupName }}

stages:
  - stage: PowerBImanageResources
    jobs:
      - job: PowerBImanageResources
        steps:
          - template: ../powerbi_manage_resources_template.yaml
            parameters:
              environment: ${{ variables.environment }}
              azureServiceConnection: ${{ variables.azureServiceConnection }}
              variableGroupName: ${{ variables.variableGroupName }}
              ms_fabric_workspaces: ${{ variables.ms_fabric_workspaces }}
              service_principal_id: ${{ variables.service_principal_id }}
              tenant_id: ${{ variables.tenant_id }}
              devops_admin_principal_id: ${{ variables.devops_admin_principal_id }}